### ISSUE TITLE
[1.10.2] Walia/HWYLA Support

### ISSUE THREAD

**Issue by Dreghert** [RoBrit/Moo-Fluids#71]
@TheRoBrit Hello! First of, thank you for your work on this. It is a great mod!

However, it does not work properly with Walia, HWYLA, or the One Probe to display fluid type. I would like to know why ThexXTURBOXx 's file mentioned in [Issue #45](https://github.com/TheRoBrit/Moo-Fluids/issues/45) works beautifully with Hwyla for 1.10.2, and your official release still does not. I understand not supporting his build of the mod, but you could at least take a look at it, to try and figure out what he did right.

You have stated in numerous issue posts about this that you were working on it, or that it was fixed, but it has been over a year now at least and it is still not working. And yet, for more than half that time, a working file has sat completely ignored by you.

I don't know, just seems silly to completely disregard a potential fix just because someone else came up with it.

**Comment by ThexXTURBOXx** [comment]
Added a PR
